clc;
clear all;
close all;
N=input('Input length :');
L=input('Down Sampling Factor :');
fo=input('Input signal Frequency :');
n=0:N-1;
x=sin(2*pi*fo*n);
y=x([1:L:length(x)]);
subplot(2,1,1);
stem(n,x);
xlabel('Time index n');
ylabel('Amplitude');
title('Input Sequence');
subplot(2,1,2);
stem(0:length(y)-1,y);
xlabel('Time index x');
ylabel('Amplitude');
title(['Output Sequence up sampled by ',num2str(L)]);